FROM node:latest

WORKDIR /app

ENV NODE_ENV=production

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps/platform/package.json apps/platform/

RUN pnpm install

COPY . .

WORKDIR /app/apps/platform
RUN pnpm build

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]


